/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package generators.test

import templates.*
import java.io.BufferedWriter
import java.io.File

object IsSortedTestGenerator {
    fun generate() {
        forEachIsSortedFamily { family, primitive -> generate(family, primitive) }
    }

    private fun generate(family: Family, primitive: PrimitiveType? = null) {
        val collectionClass = collectionClassName(family, primitive)
        val ctor = constructorName(family, primitive)
        val config = isSortedConfigFor(primitive)
        val emptyCollection = if (primitive == null) "$ctor<String>()" else "$ctor()"
        val fpTypes = when (primitive) {
            null -> listOf(PrimitiveType.Double, PrimitiveType.Float)
            PrimitiveType.Float, PrimitiveType.Double -> listOf(primitive)
            else -> emptyList()
        }

        val className = "IsSorted${collectionClass}Test"
        val file = File("libraries/stdlib/test/generated/issorted/$className.kt")
        file.parentFile.mkdirs()
        file.bufferedWriter().use { writer ->
            writer.apply {
                writeHeader(className)
                writeIsSortedTest(ctor, config, emptyCollection, descending = false)
                writeIsSortedTest(ctor, config, emptyCollection, descending = true)
                writeIsSortedWithTest(ctor, config, emptyCollection)
                writeIsSortedByTest(ctor, config, emptyCollection, descending = false)
                writeIsSortedByTest(ctor, config, emptyCollection, descending = true)
                for (fpType in fpTypes) {
                    writeFpTests(ctor, fpType)
                }
                appendLine("}")
            }
        }
    }

    private fun BufferedWriter.writeHeader(className: String) {
        appendLine(COPYRIGHT_NOTICE)
        appendLine()
        appendLine("package test.generated.issorted")
        appendLine()
        appendLine(autoGeneratedWarning("IsSortedTestGenerator.kt"))
        appendLine()
        appendLine("import kotlin.test.*")
        appendLine()
        appendLine("class $className {")
    }

    private fun BufferedWriter.writeIsSortedTest(ctor: String, config: IsSortedTypeConfig, emptyCollection: String, descending: Boolean) {
        val funcName = if (descending) "isSortedDescending" else "isSorted"
        val sorted = config.sortedValues
        val equalElement = sorted[1]
        val ascValues = sorted.joinToString()
        val descValues = sorted.reversed().joinToString()
        val expectedSorted = if (descending) descValues else ascValues
        val expectedUnsorted = if (descending) ascValues else descValues
        appendLine(
            """
    @Test
    fun $funcName() {
        assertTrue($emptyCollection.$funcName())
        assertTrue($ctor(${sorted.take(1).joinToString()}).$funcName())
        assertTrue($ctor($expectedSorted).$funcName())
        assertFalse($ctor($expectedUnsorted).$funcName())
        assertFalse($ctor(${config.unsortedValues.joinToString()}).$funcName())
        assertTrue($ctor($equalElement, $equalElement, $equalElement).$funcName())
    }"""
        )
    }

    private fun BufferedWriter.writeIsSortedWithTest(ctor: String, config: IsSortedTypeConfig, emptyCollection: String) {
        val sorted = config.sortedValues
        val unsorted = config.unsortedValues
        val caseInsensitiveLines = config.caseInsensitiveValues?.let { (sorted, unsorted) ->
            """
        assertTrue($ctor(${sorted.joinToString()}).isSortedWith(String.CASE_INSENSITIVE_ORDER))
        assertFalse($ctor(${unsorted.joinToString()}).isSortedWith(String.CASE_INSENSITIVE_ORDER))"""
        } ?: ""
        appendLine(
            """
    @Test
    fun isSortedWith() {
        assertTrue($emptyCollection.isSortedWith(naturalOrder()))
        assertTrue($ctor(${sorted.joinToString()}).isSortedWith(naturalOrder()))
        assertTrue($ctor(${sorted.reversed().joinToString()}).isSortedWith(reverseOrder()))
        assertFalse($ctor(${unsorted.joinToString()}).isSortedWith(naturalOrder()))$caseInsensitiveLines
    }"""
        )
    }

    private fun BufferedWriter.writeIsSortedByTest(ctor: String, config: IsSortedTypeConfig, emptyCollection: String, descending: Boolean) {
        val funcName = if (descending) "isSortedByDescending" else "isSortedBy"
        val selectorExpr = config.selectorExpr
        val sortedValues = if (descending) config.selectorSortedValues.reversed() else config.selectorSortedValues
        val unsortedValues = if (descending) config.selectorSortedValues else config.selectorSortedValues.reversed()
        appendLine(
            """
    @Test
    fun $funcName() {
        assertTrue($emptyCollection.$funcName { it })
        assertTrue($ctor(${sortedValues.joinToString()}).$funcName { $selectorExpr })
        assertFalse($ctor(${unsortedValues.joinToString()}).$funcName { $selectorExpr })
    }"""
        )
    }

    private fun BufferedWriter.writeFpTests(ctor: String, fpType: PrimitiveType) {
        val typeName = fpType.name
        val suffix = if (fpType == PrimitiveType.Float) "f" else ""
        val nanVal = "$typeName.NaN"
        val zeroPos = "0.0$suffix"
        val zeroNeg = "-0.0$suffix"
        val val1 = "1.0$suffix"
        val val2 = "2.0$suffix"
        appendLine(
            """
    @Test
    fun isSortedNaN$typeName() {
        assertTrue($ctor($val1, $val2, $nanVal).isSorted())
        assertFalse($ctor($nanVal, $val1, $val2).isSorted())
        assertFalse($ctor($val1, $nanVal, $val2).isSorted())
        assertTrue($ctor($nanVal, $nanVal).isSorted())
        assertTrue($ctor($nanVal, $val2, $val1).isSortedDescending())
        assertFalse($ctor($val2, $val1, $nanVal).isSortedDescending())
    }

    @Test
    fun isSortedNegativeZero$typeName() {
        assertTrue($ctor($zeroNeg, $zeroPos).isSorted())
        assertFalse($ctor($zeroPos, $zeroNeg).isSorted())
        assertTrue($ctor($zeroPos, $zeroNeg).isSortedDescending())
        assertFalse($ctor($zeroNeg, $zeroPos).isSortedDescending())
    }"""
        )
    }
}
