/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package generators.test

import templates.*
import java.io.BufferedWriter
import java.io.File

object IsSortedSampleGenerator {
    fun generate() {
        forEachIsSortedFamily { family, primitive -> generate(family, primitive) }
    }

    private fun generate(family: Family, primitive: PrimitiveType? = null) {
        val collectionClass = collectionClassName(family, primitive)
        val ctor = constructorName(family, primitive)
        val config = isSortedConfigFor(primitive)
        val sorted = config.sampleSortedValues
        val unsorted = swapAdjacentPair(sorted)
        val className = "IsSorted${collectionClass}Samples"
        val file = File("libraries/stdlib/samples/test/samples/generated/issorted/$className.kt")
        file.parentFile.mkdirs()
        file.bufferedWriter().use { writer ->
            writer.apply {
                val needsAbsImport = config.sampleSelectorAssertions.any { it.first.contains("abs(") }
                writeHeader(className, needsAbsImport)

                writeSimpleSample("isSorted", ctor, sorted, unsorted)

                val descSorted = sorted.reversed()
                val descUnsorted = swapAdjacentPair(descSorted)
                writeSimpleSample("isSortedDescending", ctor, descSorted, descUnsorted)

                writeSelectorSample("isSortedWith", ctor, config.sampleSelectorValues, config.sampleSelectorAssertions) { selector ->
                    "isSortedWith(compareBy { $selector })"
                }

                writeSelectorSample("isSortedBy", ctor, config.sampleSelectorValues, config.sampleSelectorAssertions) { selector ->
                    "isSortedBy { $selector }"
                }

                writeSelectorSample(
                    "isSortedByDescending", ctor, config.sampleSelectorValues.reversed(), config.sampleSelectorAssertions
                ) { selector ->
                    "isSortedByDescending { $selector }"
                }

                appendLine("}")
            }
        }
    }

    private fun BufferedWriter.writeHeader(className: String, needsAbsImport: Boolean) {
        appendLine(COPYRIGHT_NOTICE)
        appendLine()
        appendLine("package samples.generated.issorted")
        appendLine()
        appendLine(autoGeneratedWarning("IsSortedSampleGenerator.kt"))
        appendLine()
        appendLine("import samples.*")
        if (needsAbsImport) {
            appendLine("import kotlin.math.abs")
        }
        appendLine()
        appendLine("class $className {")
    }

    private fun BufferedWriter.writeSimpleSample(
        name: String,
        collectionOf: String,
        sortedValues: List<String>,
        unsortedValues: List<String>,
    ) {
        val sortedArgs = sortedValues.joinToString(", ")
        val unsortedArgs = unsortedValues.joinToString(", ")
        appendLine(
            """
    @Sample
    fun $name() {
        val sorted = $collectionOf($sortedArgs)
        assertPrints(sorted.$name(), "true")

        val unsorted = $collectionOf($unsortedArgs)
        assertPrints(unsorted.$name(), "false")
    }"""
        )
    }

    private fun BufferedWriter.writeSelectorSample(
        name: String,
        collectionOf: String,
        selectorValues: List<String>,
        assertions: List<Pair<String, Boolean>>,
        callExpr: (String) -> String,
    ) {
        val args = selectorValues.joinToString(", ")
        val assertLines = assertions.joinToString("\n") { (selector, expected) ->
            "        assertPrints(values.${callExpr(selector)}, \"$expected\")"
        }
        appendLine(
            """
    @Sample
    fun $name() {
        val values = $collectionOf($args)
$assertLines
    }"""
        )
    }
}
