/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package generators.test

import templates.*
import java.io.BufferedWriter

object IsSortedTestGenerator {
    fun generate() {
        forEachIsSortedFamily { family, primitive -> generate(family, primitive) }
    }

    private fun generate(family: Family, primitive: PrimitiveType? = null) {
        val collectionClass = collectionClassName(family, primitive)
        val ctor = constructorName(family, primitive)
        val config = isSortedConfigFor(primitive)
        val emptyCollection = if (primitive == null) "$ctor<String>()" else "$ctor()"
        val fpTypes = when (primitive) {
            null -> PrimitiveType.floatingPointPrimitives.toList()
            in PrimitiveType.floatingPointPrimitives -> listOf(primitive)
            else -> emptyList()
        }

        val className = "IsSorted${collectionClass}Test"
        writeGeneratedFile("libraries/stdlib/test/generated/issorted/$className.kt") {
            writeHeader(className)
            writeIsSortedTest(ctor, config, emptyCollection, descending = false)
            writeIsSortedTest(ctor, config, emptyCollection, descending = true)
            writeIsSortedWithTest(ctor, config, emptyCollection)
            writeIsSortedByTest(ctor, config, emptyCollection, descending = false)
            writeIsSortedByTest(ctor, config, emptyCollection, descending = true)
            if (primitive == null || primitive == PrimitiveType.Int) {
                writeIsSortedByNullSelectorTest(ctor, primitive)
            }
            for (fpType in fpTypes) {
                writeFpTests(ctor, fpType)
            }
            appendLine("}")
        }
    }

    private fun BufferedWriter.writeHeader(className: String) {
        appendLine(COPYRIGHT_NOTICE)
        appendLine()
        appendLine("package test.generated.issorted")
        appendLine()
        appendLine(autoGeneratedWarning("IsSortedTestGenerator.kt"))
        appendLine()
        appendLine("import kotlin.test.*")
        appendLine()
        appendLine("class $className {")
    }

    private fun BufferedWriter.writeIsSortedTest(ctor: String, config: IsSortedTypeConfig, emptyCollection: String, descending: Boolean) {
        val funcName = if (descending) "isSortedDescending" else "isSorted"
        val orderedValues = if (descending) config.sortedValues.reversed() else config.sortedValues
        val reversedValues = orderedValues.reversed()
        val equalElement = config.sortedValues[1]
        appendLine(
            """
    @Test
    fun $funcName() {
        assertTrue($emptyCollection.$funcName())
        assertTrue($ctor(${config.sortedValues.first()}).$funcName())
        assertTrue($ctor(${orderedValues.joinToString()}).$funcName())
        assertFalse($ctor(${reversedValues.joinToString()}).$funcName())
        assertFalse($ctor(${config.unsortedValues.joinToString()}).$funcName())
        assertTrue($ctor($equalElement, $equalElement, $equalElement).$funcName())
    }"""
        )
    }

    private fun BufferedWriter.writeIsSortedWithTest(ctor: String, config: IsSortedTypeConfig, emptyCollection: String) {
        val sorted = config.sortedValues
        val unsorted = config.unsortedValues
        val caseInsensitiveLines = config.caseInsensitiveValues?.let { (sorted, unsorted) ->
            """
        assertTrue($ctor(${sorted.joinToString()}).isSortedWith(String.CASE_INSENSITIVE_ORDER))
        assertFalse($ctor(${unsorted.joinToString()}).isSortedWith(String.CASE_INSENSITIVE_ORDER))"""
        } ?: ""
        appendLine(
            """
    @Test
    fun isSortedWith() {
        assertTrue($emptyCollection.isSortedWith(naturalOrder()))
        assertTrue($ctor(${sorted.joinToString()}).isSortedWith(naturalOrder()))
        assertTrue($ctor(${sorted.reversed().joinToString()}).isSortedWith(reverseOrder()))
        assertFalse($ctor(${unsorted.joinToString()}).isSortedWith(naturalOrder()))$caseInsensitiveLines
    }"""
        )
    }

    private fun BufferedWriter.writeIsSortedByTest(ctor: String, config: IsSortedTypeConfig, emptyCollection: String, descending: Boolean) {
        val funcName = if (descending) "isSortedByDescending" else "isSortedBy"
        val selectorExpr = config.selectorExpr
        val sortedValues = if (descending) config.selectorSortedValues.reversed() else config.selectorSortedValues
        val reversedValues = sortedValues.reversed()
        val swappedValues = swapAdjacentPair(sortedValues)
        appendLine(
            """
    @Test
    fun $funcName() {
        assertTrue($emptyCollection.$funcName { $selectorExpr })
        assertTrue($ctor(${sortedValues.first()}).$funcName { $selectorExpr })
        assertTrue($ctor(${sortedValues.joinToString()}).$funcName { $selectorExpr })
        assertFalse($ctor(${reversedValues.joinToString()}).$funcName { $selectorExpr })
        assertFalse($ctor(${swappedValues.joinToString()}).$funcName { $selectorExpr })
        assertTrue($ctor(${sortedValues.joinToString()}).$funcName { 0 })
    }"""
        )
    }

    private fun BufferedWriter.writeIsSortedByNullSelectorTest(ctor: String, primitive: PrimitiveType?) {
        val a = if (primitive == null) "\"a\"" else "1"
        val b = if (primitive == null) "\"b\"" else "2"
        val nullSelectorTypeArgs = if (primitive == null) "<String, String>" else "<Int>"
        val conditionalNullTypeArgs = if (primitive == null) "" else "<Int>"
        appendLine(
            """
    @Test
    fun isSortedByNullSelector() {
        assertTrue($ctor($b, $a).isSortedBy$nullSelectorTypeArgs { null })
        assertTrue($ctor($a, $a, $b).isSortedBy$conditionalNullTypeArgs { if (it == $a) null else it })
        assertFalse($ctor($b, $a).isSortedBy$conditionalNullTypeArgs { if (it == $a) null else it })
        assertTrue($ctor($b, $a).isSortedByDescending$conditionalNullTypeArgs { if (it == $a) null else it })
        assertFalse($ctor($a, $b).isSortedByDescending$conditionalNullTypeArgs { if (it == $a) null else it })
    }"""
        )
    }

    private fun BufferedWriter.writeFpTests(ctor: String, fpType: PrimitiveType) {
        val typeName = fpType.name
        val suffix = if (fpType == PrimitiveType.Float) "f" else ""
        val nanVal = "$typeName.NaN"
        val zeroPos = "0.0$suffix"
        val zeroNeg = "-0.0$suffix"
        val val1 = "1.0$suffix"
        val val2 = "2.0$suffix"
        appendLine(
            """
    @Test
    fun isSortedNaN$typeName() {
        assertTrue($ctor($val1, $val2, $nanVal).isSorted())
        assertFalse($ctor($nanVal, $val1, $val2).isSorted())
        assertFalse($ctor($val1, $nanVal, $val2).isSorted())
        assertTrue($ctor($nanVal, $nanVal).isSorted())
        assertTrue($ctor($nanVal, $val2, $val1).isSortedDescending())
        assertFalse($ctor($val2, $val1, $nanVal).isSortedDescending())
        assertFalse($ctor($val2, $nanVal, $val1).isSortedDescending())
        assertTrue($ctor($nanVal, $nanVal).isSortedDescending())
    }

    @Test
    fun isSortedNegativeZero$typeName() {
        assertTrue($ctor($zeroNeg, $zeroPos).isSorted())
        assertFalse($ctor($zeroPos, $zeroNeg).isSorted())
        assertTrue($ctor($zeroPos, $zeroNeg).isSortedDescending())
        assertFalse($ctor($zeroNeg, $zeroPos).isSortedDescending())
    }

    @Test
    fun isSortedWithNaN$typeName() {
        assertTrue($ctor($val1, $val2, $nanVal).isSortedWith(naturalOrder()))
        assertFalse($ctor($nanVal, $val1, $val2).isSortedWith(naturalOrder()))
        assertTrue($ctor($nanVal, $val2, $val1).isSortedWith(reverseOrder()))
        assertFalse($ctor($val2, $val1, $nanVal).isSortedWith(reverseOrder()))
    }

    @Test
    fun isSortedWithNegativeZero$typeName() {
        assertTrue($ctor($zeroNeg, $zeroPos).isSortedWith(naturalOrder()))
        assertFalse($ctor($zeroPos, $zeroNeg).isSortedWith(naturalOrder()))
        assertTrue($ctor($zeroPos, $zeroNeg).isSortedWith(reverseOrder()))
        assertFalse($ctor($zeroNeg, $zeroPos).isSortedWith(reverseOrder()))
    }

    @Test
    fun isSortedByNaN$typeName() {
        assertTrue($ctor($val1, $val2, $nanVal).isSortedBy { it })
        assertFalse($ctor($nanVal, $val1, $val2).isSortedBy { it })
        assertFalse($ctor($val1, $nanVal, $val2).isSortedBy { it })
        assertTrue($ctor($nanVal, $nanVal).isSortedBy { it })
        assertTrue($ctor($nanVal, $val2, $val1).isSortedByDescending { it })
        assertFalse($ctor($val2, $val1, $nanVal).isSortedByDescending { it })
        assertFalse($ctor($val2, $nanVal, $val1).isSortedByDescending { it })
        assertTrue($ctor($nanVal, $nanVal).isSortedByDescending { it })
    }

    @Test
    fun isSortedByNegativeZero$typeName() {
        assertTrue($ctor($zeroNeg, $zeroPos).isSortedBy { it })
        assertFalse($ctor($zeroPos, $zeroNeg).isSortedBy { it })
        assertTrue($ctor($zeroPos, $zeroNeg).isSortedByDescending { it })
        assertFalse($ctor($zeroNeg, $zeroPos).isSortedByDescending { it })
    }"""
        )
    }
}
