/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package generators.test

import templates.*
import java.io.BufferedWriter

object IsSortedSampleGenerator {
    fun generate() {
        forEachIsSortedFamily { family, primitive -> generate(family, primitive) }
    }

    private fun generate(family: Family, primitive: PrimitiveType? = null) {
        val collectionClass = collectionClassName(family, primitive)
        val ctor = constructorName(family, primitive)
        val config = isSortedConfigFor(primitive)
        val sorted = config.sampleSortedValues
        val unsorted = swapAdjacentPair(sorted)
        val className = "IsSorted${collectionClass}Samples"
        writeGeneratedFile("libraries/stdlib/samples/test/samples/generated/issorted/$className.kt") {
            val needsAbsImport = config.sampleNeedsAbsImport
            writeHeader(className, needsAbsImport)
            writeSimpleSample("isSorted", ctor, sorted, unsorted)
            val descSorted = sorted.reversed()
            val descUnsorted = swapAdjacentPair(descSorted)
            writeSimpleSample("isSortedDescending", ctor, descSorted, descUnsorted)
            writeComparatorSample(ctor, sorted, config.caseInsensitiveValues?.sorted)
            writeSelectorSample("isSortedBy", ctor, config.sampleSelectorValues, config.sampleSelectorAssertions)
            writeSelectorSample(
                "isSortedByDescending", ctor, config.sampleSelectorValues.reversed(), config.sampleSelectorAssertions
            )
            appendLine("}")
        }
    }

    private fun BufferedWriter.writeHeader(className: String, needsAbsImport: Boolean) {
        appendLine(COPYRIGHT_NOTICE)
        appendLine()
        appendLine("package samples.generated.issorted")
        appendLine()
        appendLine(autoGeneratedWarning("IsSortedSampleGenerator.kt"))
        appendLine()
        appendLine("import samples.*")
        if (needsAbsImport) {
            appendLine("import kotlin.math.abs")
        }
        appendLine()
        appendLine("class $className {")
    }

    private fun BufferedWriter.writeSimpleSample(
        name: String,
        ctor: String,
        sortedValues: List<String>,
        unsortedValues: List<String>,
    ) {
        val sortedArgs = sortedValues.joinToString(", ")
        val unsortedArgs = unsortedValues.joinToString(", ")
        appendLine(
            """
    @Sample
    fun $name() {
        val sorted = $ctor($sortedArgs)
        assertPrints(sorted.$name(), "true")

        val unsorted = $ctor($unsortedArgs)
        assertPrints(unsorted.$name(), "false")
    }"""
        )
    }

    private fun BufferedWriter.writeComparatorSample(
        ctor: String,
        sortedValues: List<String>,
        caseInsensitiveSortedValues: List<String>?,
    ) {
        val sortedArgs = sortedValues.joinToString(", ")
        val reversedArgs = sortedValues.reversed().joinToString(", ")
        val caseInsensitiveLines = caseInsensitiveSortedValues?.let { values ->
            val caseArgs = values.joinToString(", ")
            """

        val caseInsensitive = $ctor($caseArgs)
        assertPrints(caseInsensitive.isSortedWith(String.CASE_INSENSITIVE_ORDER), "true")"""
        } ?: ""
        appendLine(
            """
    @Sample
    fun isSortedWith() {
        val sorted = $ctor($sortedArgs)
        assertPrints(sorted.isSortedWith(naturalOrder()), "true")
        assertPrints(sorted.isSortedWith(reverseOrder()), "false")

        val reversed = $ctor($reversedArgs)
        assertPrints(reversed.isSortedWith(reverseOrder()), "true")$caseInsensitiveLines
    }"""
        )
    }

    private fun BufferedWriter.writeSelectorSample(
        name: String,
        ctor: String,
        selectorValues: List<String>,
        assertions: List<Pair<String, Boolean>>,
    ) {
        val args = selectorValues.joinToString(", ")
        val assertLines = assertions.joinToString("\n") { (selector, expected) ->
            "        assertPrints(values.$name { $selector }, \"$expected\")"
        }
        appendLine(
            """
    @Sample
    fun $name() {
        val values = $ctor($args)
$assertLines
    }"""
        )
    }
}
