/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package generators.test

import templates.*
import templates.Family.*
import templates.PrimitiveType
import java.io.BufferedWriter
import java.io.File

object IsSortedTestGenerator {
    fun generate() {
        generate(Iterables)
        generate(Sequences)
        generate(ArraysOfObjects)
        for (primitive in PrimitiveType.defaultPrimitives) {
            generate(ArraysOfPrimitives, primitive)
        }
        for (primitive in PrimitiveType.unsignedPrimitives) {
            generate(ArraysOfUnsigned, primitive)
        }
    }

    private class TestTypeConfig(
        val sortedValues: List<String>,
        val unsortedValues: List<String> = listOf(sortedValues[1], sortedValues[0], sortedValues[2]),
        val selectorExpr: String = "it",
        val selectorSortedValues: List<String> = sortedValues,
        val caseInsensitiveValues: Pair<List<String>, List<String>>? = null,
    )

    private fun configFor(primitive: PrimitiveType?): TestTypeConfig = when (primitive) {
        PrimitiveType.Char -> TestTypeConfig(
            sortedValues = listOf("'a'", "'b'", "'c'")
        )
        PrimitiveType.Boolean -> TestTypeConfig(
            sortedValues = listOf("false", "true", "true"),
            selectorExpr = "it.compareTo(false)"
        )
        null -> TestTypeConfig(
            sortedValues = listOf("\"a\"", "\"b\"", "\"c\""),
            selectorExpr = "it.length",
            selectorSortedValues = listOf("\"a\"", "\"bb\"", "\"ccc\""),
            caseInsensitiveValues = listOf("\"Apple\"", "\"banana\"", "\"Cherry\"") to listOf("\"banana\"", "\"Apple\"", "\"Cherry\""),
        )
        else -> {
            val suffix = when (primitive) {
                PrimitiveType.Long -> "L"
                PrimitiveType.ULong -> "uL"
                in PrimitiveType.unsignedPrimitives -> "u"
                PrimitiveType.Float -> ".0f"
                PrimitiveType.Double -> ".0"
                else -> ""
            }
            TestTypeConfig(sortedValues = listOf("1$suffix", "2$suffix", "3$suffix"))
        }
    }

    private fun generate(family: Family, primitive: PrimitiveType? = null) {
        val collectionClass = when (family) {
            Iterables, Sequences -> family.toString()
            ArraysOfObjects -> "Array"
            ArraysOfPrimitives, ArraysOfUnsigned -> "${primitive!!}Array"
            else -> error(family)
        }

        val isGeneric = primitive == null
        val ctor = when (family) {
            Iterables -> "listOf"
            Sequences -> "sequenceOf"
            ArraysOfObjects -> "arrayOf"
            ArraysOfPrimitives, ArraysOfUnsigned -> "${primitive!!.name.lowercase()}ArrayOf"
        }
        val config = configFor(primitive)
        val emptyCollection = if (isGeneric) "$ctor<Int>()" else "$ctor()"
        val fpTypes = when {
            isGeneric -> listOf(PrimitiveType.Double, PrimitiveType.Float)
            primitive.isFloatingPoint() -> listOf(primitive)
            else -> emptyList()
        }

        val className = "IsSorted${collectionClass}Test"
        val file = File("libraries/stdlib/test/generated/issorted/$className.kt")
        file.parentFile.mkdirs()
        file.bufferedWriter().use { writer ->
            writer.apply {
                writeHeader(className)
                writeIsSortedTest(ctor, config, emptyCollection, descending = false)
                writeIsSortedTest(ctor, config, emptyCollection, descending = true)
                writeIsSortedWithTest(ctor, config, emptyCollection)
                writeIsSortedByTest(ctor, config, emptyCollection, descending = false)
                writeIsSortedByTest(ctor, config, emptyCollection, descending = true)
                for (fpType in fpTypes) {
                    writeFpTests(ctor, fpType)
                }
                appendLine("}")
            }
        }
    }

    private fun BufferedWriter.writeHeader(className: String) {
        appendLine(COPYRIGHT_NOTICE)
        appendLine()
        appendLine("package test.generated.issorted")
        appendLine()
        appendLine(autoGeneratedWarning("IsSortedTestGenerator.kt"))
        appendLine()
        appendLine("import kotlin.test.*")
        appendLine()
        appendLine("class $className {")
    }

    private fun BufferedWriter.writeIsSortedTest(ctor: String, config: TestTypeConfig, emptyCollection: String, descending: Boolean) {
        val funcName = if (descending) "isSortedDescending" else "isSorted"
        val sorted = config.sortedValues
        val equalElement = sorted[1]
        val ascValues = sorted.joinToString()
        val descValues = sorted.reversed().joinToString()
        val trueSorted = if (descending) descValues else ascValues
        val falseSorted = if (descending) ascValues else descValues
        appendLine(
            """
    @Test
    fun $funcName() {
        assertTrue($emptyCollection.$funcName())
        assertTrue($ctor(${sorted.take(1).joinToString()}).$funcName())
        assertTrue($ctor($trueSorted).$funcName())
        assertFalse($ctor($falseSorted).$funcName())
        assertFalse($ctor(${config.unsortedValues.joinToString()}).$funcName())
        assertTrue($ctor($equalElement, $equalElement, $equalElement).$funcName())
    }"""
        )
    }

    private fun BufferedWriter.writeIsSortedWithTest(ctor: String, config: TestTypeConfig, emptyCollection: String) {
        val sorted = config.sortedValues
        val unsorted = config.unsortedValues
        val caseInsensitiveLines = config.caseInsensitiveValues?.let { (sorted, unsorted) ->
            """
        assertTrue($ctor(${sorted.joinToString()}).isSortedWith(String.CASE_INSENSITIVE_ORDER))
        assertFalse($ctor(${unsorted.joinToString()}).isSortedWith(String.CASE_INSENSITIVE_ORDER))"""
        } ?: ""
        appendLine(
            """
    @Test
    fun isSortedWith() {
        assertTrue($emptyCollection.isSortedWith(naturalOrder()))
        assertTrue($ctor(${sorted.joinToString()}).isSortedWith(naturalOrder()))
        assertTrue($ctor(${sorted.reversed().joinToString()}).isSortedWith(reverseOrder()))
        assertFalse($ctor(${unsorted.joinToString()}).isSortedWith(naturalOrder()))$caseInsensitiveLines
    }"""
        )
    }

    private fun BufferedWriter.writeIsSortedByTest(ctor: String, config: TestTypeConfig, emptyCollection: String, descending: Boolean) {
        val funcName = if (descending) "isSortedByDescending" else "isSortedBy"
        val selectorExpr = config.selectorExpr
        val sortedValues = if (descending) config.selectorSortedValues.reversed() else config.selectorSortedValues
        val unsortedValues = if (descending) config.selectorSortedValues else config.selectorSortedValues.reversed()
        appendLine(
            """
    @Test
    fun $funcName() {
        assertTrue($emptyCollection.$funcName { it })
        assertTrue($ctor(${sortedValues.joinToString()}).$funcName { $selectorExpr })
        assertFalse($ctor(${unsortedValues.joinToString()}).$funcName { $selectorExpr })
    }"""
        )
    }

    private fun BufferedWriter.writeFpTests(ctor: String, fpType: PrimitiveType) {
        val typeName = fpType.name
        val suffix = if (fpType == PrimitiveType.Float) "f" else ""
        val nanVal = "$typeName.NaN"
        val zeroPos = "0.0$suffix"
        val zeroNeg = "-0.0$suffix"
        val val1 = "1.0$suffix"
        val val2 = "2.0$suffix"
        appendLine(
            """
    @Test
    fun isSortedNaN$typeName() {
        assertTrue($ctor($val1, $val2, $nanVal).isSorted())
        assertFalse($ctor($nanVal, $val1, $val2).isSorted())
        assertFalse($ctor($val1, $nanVal, $val2).isSorted())
        assertTrue($ctor($nanVal, $nanVal).isSorted())
        assertTrue($ctor($nanVal, $val2, $val1).isSortedDescending())
        assertFalse($ctor($val2, $val1, $nanVal).isSortedDescending())
    }

    @Test
    fun isSortedNegativeZero$typeName() {
        assertTrue($ctor($zeroNeg, $zeroPos).isSorted())
        assertFalse($ctor($zeroPos, $zeroNeg).isSorted())
        assertTrue($ctor($zeroPos, $zeroNeg).isSortedDescending())
        assertFalse($ctor($zeroNeg, $zeroPos).isSortedDescending())
    }"""
        )
    }
}
